version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: example_db
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example -d example_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example_web
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: example.settings
      DATABASE_URL: postgres://example:example@db:5432/example_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: ["CMD-SHELL", "python manage.py check --database default --settings example.settings"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data: