# Generated by Django 5.2.1 on 2025-05-18 08:24

from django.db import migrations
import os


def _load(apps, schema_editor):
    from aus_address.utils import populate_locations
    data_file_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'data', 'australian_postcodes.csv')
    populate_locations(data_file_path)


def _reverse(apps, schema_editor):
    """
    Reverse the migration by deleting all records in the State, Suburb, and Postcode models.
    This is a simple cleanup operation and does not restore the original state of the database."""
    State = apps.get_model('aus_address', 'State')
    Location = apps.get_model('aus_address', 'Location')
    State.objects.all().delete()
    Location.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('aus_address', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(_load, _reverse),
    ]
